#!/bin/bash
#This file installs arduino and ino tools
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
LANG=C perl -e exit
echo Installing Arduino ...
sudo apt-get -y install arduino-core
sudo usermod -aG dialout $(whoami)
echo "Added $(whoami) to dialout group"
sleep 2
echo Installing ino tools ...
sudo apt-get -y install phython
sudo apt-get -y install python-pip
sudo apt-get -y install picocom
sudo pip install ino
sleep 2

