#!/bin/bash
#This file installs arduino and ino tools
echo Installing Arduino ...
sudo apt-get -y install arduino
sudo usermod -aG dialout $(whoami)
echo "Added $(whoami) to dialout group"
sleep 2
echo Installing ino tools ...
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
LANG=C perl -e exit
pip install ino
sleep 2

