#!/bin/bash
#This file installs arduino and ino tools
echo Installing Arduino ...
sudo apt-get -y install arduino
sudo usermod -aG dialout $(whoami)
echo "Added $(whoami) to dialout group"
sleep 2
echo Installing ino tools ...
sudo apt-get -y install python-pip
pip install ino
sleep 2

