




.build/mega2560/src/MinhoTeamNovoHardware.cpp : src/MinhoTeamNovoHardware.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/MinhoTeamNovoHardware.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/MinhoTeamNovoHardware.cpp
	@true

